kuris-bot:
  server:
    url: "http://192.168.50.183:5700"
    qq: 2198336792
http:
  proxy:
    url: "127.0.0.1"
    port: 10808
spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.50.183:3306/Kurisu?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowMultiQueries=true
      username: root
      password: 12345678
      driver-class-name: com.mysql.jdbc.Driver
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      stat-view-servlet:
        login-username: root
        login-password: 12345678
        url-pattern: /druid/*
        enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true