kuris-bot:
  server:
    url: "http://192.168.50.183:5700"
    qq: 2198336792
http:
  proxy:
    url: "127.0.0.1"
    port: 10808
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.50.183:3306/Kurisu?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 12345678
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true